app_name: air-quality-collector
environment: production
debug: false

storage:
  base_path: data
  checkpoint_dir: data/checkpoints
  batch_size: 1000
  file_format: csv

cache:
  type: memory
  ttl: 300
  max_size: 1000

logging:
  level: INFO
  format: json
  file_path: logs/app.log
  rotate_size: 10000000
  backup_count: 5

metrics:
  enabled: true
  type: prometheus
  namespace: airquality
  port: 9090
  flush_interval: 10

parallel_downloads: true
max_concurrent_locations: 5
max_concurrent_sensors: 10

data_sources:
  - name: openaq
    type: openaq
    enabled: true
    config:
      base_url: https://api.openaq.org/v3
      rate_limit_per_key: 60
      timeout: 30
      retry_count: 3

  - name: purpleair
    type: purpleair
    enabled: false
    config:
      base_url: https://api.purpleair.com/v1
      rate_limit_per_key: 100
      timeout: 30

  - name: waqi
    type: waqi
    enabled: false
    config:
      base_url: https://api.waqi.info
      rate_limit_per_key: 1000
      timeout: 30